modLoader="javafml"
loaderVersion="[41,)"
issueTrackerURL="https://github.com/MC-U-Team/Basic-Discord-Rich-Presence/issues"
license="Apache-2.0 License"

[[mods]]
	modId="musicplayer"
	version="${file.jarVersion}"
	displayName="Basic Discord Rich Presence"
	displayURL="https://u-team.info/mods/basicdiscordrichpresence"
	updateJSONURL="https://api.u-team.info/update/basicdiscordrichpresence.json"
	logoFile="logo.png"
	credits="Team U-Team"
	authors="HyCraftHD"
	description="This mod adds a basic discord rich presence. The rich presence was in uteamcore until 1.16.4, now for 1.16.5+ it's a seperate project."
		
	[[dependencies.basicdiscordrichpresence]]
		modId="forge"
		mandatory=true
		versionRange="[41.0.45,)"
		ordering="NONE"
		side="BOTH"
	
	[[dependencies.basicdiscordrichpresence]]
		modId="minecraft"
		mandatory=true
		versionRange="[1.19]"
		ordering="NONE"
		side="BOTH"